# Generated by Django 5.0.7 on 2024-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_testimonial_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
